import Providers from "@/redux/providers";
import "./globals.css";

export const metadata = {
  title: "Redux Toolkit",
  description: "Generated by Next-RTK",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
